/** Common trivial names listed or implied in the HKDSE textbooks. */
export const TRIVIAL_NAMES: Record<string, string> = {
  formaldehyde: 'methanal',
  acetaldehyde: 'ethanal',
  acetone: 'propanone',
  'acetic acid': 'ethanoic acid',
  'formic acid': 'methanoic acid',
  chloroform: 'trichloromethane',
  'isopropyl alcohol': 'propan-2-ol',
  isopropanol: 'propan-2-ol',
  'methyl alcohol': 'methanol',
  methanol: 'methanol',
  'ethyl alcohol': 'ethanol',
  ethanol: 'ethanol',
  formamide: 'methanamide',
  acetamide: 'ethanamide',
  methylamine: 'methanamine',
  ethylamine: 'ethanamine',
  propylamine: 'propan-1-amine',
  butylamine: 'butan-1-amine',
  isopropylamine: 'propan-2-amine',
  'tert-butyl alcohol': '2-methylpropan-2-ol',
  't-butyl alcohol': '2-methylpropan-2-ol',
  't-butanol': '2-methylpropan-2-ol',
  'tert-butanol': '2-methylpropan-2-ol',
}
